### ISSUE TITLE
docsify 4.x roadmap

### ISSUE THREAD

**Issue by timaschew** [docsifyjs/docsify#823]
@docsifyjs/core
Before releasing 5.0 we should improve on some topics.

### v4.x

This list is open for discussion.

- [x] Agree to drop IE 10 support. Support is only available for IE 11
- [x] Remove `lib` directory from version control
- [x] find bugs which should be fixed before 5.0 and attach **4.x** milestone to them
- [x] fix selected bugs
- [ ] improve test coverage
- [x] setup browser testing (cypress for instance) ( #986 )
- [ ] Closing #657 and create a new one (since it becomes a bit messy)
- [x] fixing Lint errors and warning ( https://github.com/docsifyjs/docsify/issues/987 )

Related discussions:
https://github.com/docsifyjs/docsify/issues/657#issuecomment-458341229

---

5.0 and further:

- use [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) as default theme
- https://github.com/docsifyjs/docsify/pull/802
  - Static generation
  - New Markdown Syntax
- Drop-in-replacement for GitBook

**Comment by jhildenbiddle** [comment]
Thanks for taking this on, @timaschew. My plate is pretty full at the moment, but I'm happy to help out on specific areas upon request. Once more time becomes available, I can be more proactive about contributing. Until then, just let me know if/when you can use a hand.

**Comment by jrappen** [comment]
Using the service worker example from the docs, docsify now loads docs for the current translation only. This is possibly related to search only working for the current translation only as well (which was completely broken a short while back as discussed in jhildenbiddle/docsify-themeable#18 and worked across translations before that). Is there any reason for this?

**Comment by anikethsaha** [comment]
> New Markdown Syntax

For new markdown syntax, I would recommend using a pluggable markdown processor which can be configured using the docsify config, like [`markdown-it`](https://github.com/markdown-it/markdown-it#readme)

cc @docsifyjs/core

**Comment by anikethsaha** [comment]
@timaschew I am closing this in favor of https://github.com/docsifyjs/docsify/issues/1061

Please let me know if you think something more/less needs to be added in #1061
